[package]
name = "rustnes"
version = "0.1.0"
authors = ["Tomochika Hara <rust@thara.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
